services:
  web:
    profiles: [build]
    image: ghcr.io/ryan-willis/bean-counter:latest
    build:
      platforms:
        - linux/amd64
        - linux/arm64
      context: .
      tags: [ghcr.io/ryan-willis/bean-counter:latest]
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bean
      POSTGRES_PASSWORD: counter
      POSTGRES_DB: beancounter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    external: false
