// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin_tokens.sql

package db

import (
	"context"
)

const createAdminToken = `-- name: CreateAdminToken :one
INSERT INTO admin_tokens (token) VALUES ($1) RETURNING id, token, created_at, updated_at
`

func (q *Queries) CreateAdminToken(ctx context.Context, token string) (AdminToken, error) {
	row := q.db.QueryRow(ctx, createAdminToken, token)
	var i AdminToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminToken = `-- name: GetAdminToken :one
SELECT id, token, created_at, updated_at FROM admin_tokens WHERE token = $1 LIMIT 1
`

func (q *Queries) GetAdminToken(ctx context.Context, token string) (AdminToken, error) {
	row := q.db.QueryRow(ctx, getAdminToken, token)
	var i AdminToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
