// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminToken struct {
	ID        pgtype.UUID `json:"id"`
	Token     string      `json:"token"`
	CreatedAt int64       `json:"created_at"`
	UpdatedAt int64       `json:"updated_at"`
}

type Menu struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	CreatedAt int64       `json:"created_at"`
	UpdatedAt int64       `json:"updated_at"`
	PublicID  pgtype.Text `json:"public_id"`
}

type MenuItem struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	CreatedAt int64       `json:"created_at"`
	UpdatedAt int64       `json:"updated_at"`
}

type MenusMenuItem struct {
	FkMenuID     pgtype.UUID `json:"fk_menu_id"`
	FkMenuItemID pgtype.UUID `json:"fk_menu_item_id"`
}

type Order struct {
	ID           pgtype.UUID `json:"id"`
	MenuID       pgtype.UUID `json:"menu_id"`
	CustomerName string      `json:"customer_name"`
	CreatedAt    int64       `json:"created_at"`
	UpdatedAt    int64       `json:"updated_at"`
	Status       string      `json:"status"`
}

type OrdersMenuItem struct {
	FkOrderID    pgtype.UUID `json:"fk_order_id"`
	FkMenuItemID pgtype.UUID `json:"fk_menu_item_id"`
}
